<?php

namespace App\Type;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskFilterType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
//        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'projectsList' => [],
            "authorsList" => [],
            "ownersList" => []
        ]);

        $resolver->setAllowedTypes('projectsList', 'array');
        $resolver->setAllowedTypes('authorsList', 'array');
        $resolver->setAllowedTypes('ownersList', 'array');

    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        dd($options);
        $builder
            ->setMethod('GET')
            ->add('isCompleted', ChoiceType::class, [
                'choices' => [
                    'Да' => true,
                    'Нет' => false,
                    'Любое' => null,
                ],
                'label' => 'Выполнена'
            ])
            ->add("project", ChoiceType::class, [
                "placeholder" => "Любой",
                "required" => false,
                "choices" => $options["projectsList"],
                "choice_label" => function(?Project $entity) {
                    return $entity ? $entity -> getProjectKey() : "";
                },
            ])
            ->add("author", ChoiceType::class, [
                "placeholder" => "Любой",
                "required" => false,
                "choices" => $options["authorsList"],
                "choice_label" => function ($choice) {
                    return $choice;
                }
            ])
            ->add("project-owner", ChoiceType::class, [
                "placeholder" => "Любой",
                "required" => false,
                "choices" => $options["ownersList"],
                "choice_label" => function ($choice) {
                    return $choice;
                }
            ])
            ->add("sort-by-name", ChoiceType::class, [
                "choices" => [
                    "В лексикографическом порядке" => true,
                    "В обратном порядке" => false
                ],
                "label" => "Отсортировать по названию"
            ])
            ->add("sort-by-date", ChoiceType::class, [
                "choices" => [
                    "От старых к новым" => true,
                    "От новых к сатрым" => false
                ],
                "label" => "Отсортировать по дате"
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Применить введённые данные'
            ]);
    }


}