<?php

namespace App\Type;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskFilterType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
//        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'projects_list' => [],
            "authors_list" => [],
            "owners_list" => []
        ]);

        $resolver->setAllowedTypes('projects_list', 'array');
        $resolver->setAllowedTypes('authors_list', 'array');
        $resolver->setAllowedTypes('owners_list', 'array');

    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        dd($options);
        $builder
            ->setMethod('GET')
            ->add('isCompleted', ChoiceType::class, [
                'choices' => [
                    'Да' => true,
                    'Нет' => false,
                    'Любое' => null,
                ],
                'label' => 'Выполнена'
            ])
            ->add("filter-by-project", CheckboxType::class, [
                "label" => "Отметьте, если нужно отфильтровать по проектам",
                "required" => false
            ])
            ->add("project", ChoiceType::class, [
                "choices" => $options["projects_list"],
                "choice_label" => function(?Project $entity) {
                    return $entity ? $entity -> getProjectKey() : "";
                },
            ])
            ->add("filter-by-author", CheckboxType::class, [
                "label" => "Отметьте, если нужно отфильтровать по авторам задач",
                "required" => false
            ])
            ->add("author", ChoiceType::class, [
                "choices" => $options["authors_list"],
            ])
            ->add("filter-by-owner", CheckboxType::class, [
                "label" => "Отметьте, если нужно отфильтровать по владельцам проктов",
                "required" => false
            ])
            ->add("project-owner", ChoiceType::class, [
                "choices" => $options["owners_list"],
            ])
            ->add("sort-by-name", ChoiceType::class, [
                "choices" => [
                    "В лексикографическом порядке" => true,
                    "В обратном порядке" => false
                ],
                "label" => "Отсортировать по названию"
            ])
            ->add("sort-by-date", ChoiceType::class, [
                "choices" => [
                    "От старых к новым" => true,
                    "От новых к сатрым" => false
                ],
                "label" => "Отсортировать по дате"
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Применить введённые данные'
            ]);
    }


}