<?php

namespace App\Type;

use App\Entity\Project;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
//        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'projectsList' => [],
        ]);

        $resolver->setAllowedTypes('projectsList', 'array');

    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('description', TextareaType::class)
            ->add('dueDate', DateType::class, [
                'years' => range(2022,2023)
            ])
            ->add('project', ChoiceType::class, [
                "choices" => $options["projectsList"],
                'choice_label' => function ($choice) {
                    return $choice;
                },
                "label" => "Выберите проект",
            ])
            ->add('save', SubmitType::class)
        ;
    }
}